name: Mirror from SourceForge

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: Clone the SourceForge repository
      - name: Clone SourceForge Repository
        run: |
          git clone --depth 1 https://git.code.sf.net/p/echoes/git sourceforge
          cd sourceforge
          # Remove README from SourceForge to preserve the custom one
          rm -f README.md

      # Step 3: Sync files from SourceForge to the GitHub repository
      - name: Sync SourceForge Content
        run: |
          rsync -a --exclude='.git' sourceforge/ .
          rm -rf sourceforge # Cleanup

      # Step 4: Commit and push changes to GitHub
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Mirror update from SourceForge" || echo "No changes to commit"
          git push origin main
